version: '3.5'

services:
  app:
    container_name: app
    build: .
    ports: 
      - "4000:4000"
  db:
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:bullseye
