services:
  db:
    image: postgres:bullseye
    container_name: db
    ports: 
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/logs/postgresql/postgresql.logs
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin' ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    restart: always
    container_name: app
    ports: 
      - "4000:4000"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://admin:root@host.docker.internal:5432/mydb?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

networks:
  backend:
    name: backend
    driver: bridge
